# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoEdit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoEdit
pod 'BetterSegmentedControl', '~> 2.0'
pod 'SwiftMessages'
pod 'mobile-ffmpeg-full-gpl', '~> 4.2'
pod 'lottie-ios'
pod 'BoxSDK'

end
