# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'VideoEdit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoEdit
pod 'BetterSegmentedControl', '~> 2.0'
pod 'SwiftMessages'
pod 'mobile-ffmpeg-full-gpl', '~> 4.2'
pod 'lottie-ios'
pod 'BoxSDK'

pod 'SDWebImage'
pod 'SwiftSoup'
pod 'CryptoSwift'
pod 'Zip'
pod 'RealmSwift'

pod 'AppLovinSDK'
pod 'AppLovinMediationAdColonyAdapter'
pod 'AppLovinMediationGoogleAdapter'
pod 'AppLovinMediationIronSourceAdapter'
pod 'AppLovinMediationVungleAdapter'
pod 'AppLovinMediationUnityAdsAdapter'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
